### ISSUE TITLE
Использование git для версионирования отдельных файлов

### ISSUE THREAD

**Issue by Bringoff** [antorix/Rocket-Ministry#1]
Приветствую. Я вижу, что код добавляется и удаляется просто заливкой и удалением архива. Это несколько убивает идею git, предназначающийся для работы с версиями каждого файла, чтобы можно было видеть историю изменений каждого, а также работать нескольким людям вместе над одним и тем же кодом без проблем вроде: "и я, и он изменили что-то в одном файле, и какую версию не используй, в коде другого что-то сломается". Текущий подход ничем не отличается от использования простого облачного файлового хранилища. И это усложняет (или скорее делает практически невозможным) помощь кого-то еще в разработке данного приложения. Поэтому предлагаю рассмотреть использование git все же для версионирования.
А скачивать архив с кодом при необходимости все равно можно будет через кнопку clone & download.

**Comment by antorix** [comment]
Привет. Я понимаю, что Гит хорошо подходит для совместной работы. Но я не планирую использовать чужие наработки, кроме разве что очень редких случаев. Просто нет времени. Кроме того, простой zip-файл обычным людям проще и понятнее. Мне как раз и нужно обычное, максимально просто облачное хранилище, чтобы можно было дать людям прямую ссылку на закачку. Спасибо, что интересуешься.

**Comment by antorix** [comment]
Артём, хочу добавить, если у тебя есть какие-то идеи по улучшению или готовый код, ты смело пиши, не стесняйся. Поговорим, обсудим. И если предложение путное, я с удовольствием включу его в код. Знаешь, ты первый, кто предлагает участвовать в разработке. Поэтому мы с тобой всегда сможем найти общий язык и без интерфейса гитхаба ;)

**Comment by Bringoff** [comment]
Пока код предложить не готов, да и Python - не мой профиль. Из предложений - получение авторизованного доступа к облачному сервису пользователя с дальнейшим бекапом и восстановлением. Было бы прекрасно вообще уметь приложению делать это в фоне, как реализовано в Ministry Assistant (если бекап в облаке новее, чем локальные данные, данные с облака автоматически подтягиваются), но думаю, Python на Android не умеет держать сервисы или работать с JobScheduler-ом.
И такой момент - при скачивании архива Windows Defender на Windows 10 определяет инсталлятор в  архиве как вирус, возможно, из-за отсутствия подписи exe-шника. Прогнал по VirusTotal - примерно треть антивирусов ругается. Это может пугать кого-то. Да что там - это точно пугает :)

**Comment by antorix** [comment]
Да, возможностей движка Qpython на Android, который я использовал, не позволяют работать с облачными сервисами полноценно. Все, что можно сделать, это вручную отправлять файл в облако, перехватывая интент Android, который работает с приложениями почты и некоторых облачных сервисов. По второму пункту: да, антивирусам не нравится отсутствие цифровой подписи. Она стоила бы мне серьезных денежек. Но это не беда, exe-шник использовать необязательно. Он просто создает иконку на рабочем столе и в папке «Программы». Для запуска самой программы он не нужен. Его вообще можно сразу удалить.
